name: GitHub Actions Demo
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
    steps:
      matrix:
        node-version: [14.x]
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
         with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install
      - run: make lint